"""Emit a Markdown report of the FidelityNO sampling regimes vs real-device
calibration data. Output goes to results_prxq/device_regimes.md so the
PRXQ paper Appendix A can include it verbatim.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from physics.channels.units import (
    DEVICE_REGIMES,
    all_family_annotations,
    device_regime_table,
    gamma_from_T1,
    lambda_p_from_T2,
    depolarizing_p_from_rb,
    rb_from_depolarizing_p,
    T1_from_gamma,
    T2_from_T1_lambda_p,
)


def main() -> None:
    out = Path(__file__).resolve().parents[1] / "results_prxq" / "device_regimes.md"
    out.parent.mkdir(parents=True, exist_ok=True)

    sections = []
    sections.append("# FidelityNO sampling regimes vs real-device calibration")
    sections.append("")
    sections.append(
        "Generated by ``scripts/emit_device_regime_report.py``. Numbers in the "
        "device row are *representative* values from the cited datasheets / "
        "papers, not specific calibration runs. They establish that v1's "
        "abstract sampling ranges cover the noise levels of every modern QPU "
        "platform with the exception noted at the end."
    )
    sections.append("")
    sections.append("## A.1 Per-device reference operating points")
    sections.append("")
    sections.append(
        "Each row is a representative single-day calibration tuple. "
        "Columns: gate time, T₁, T₂, single- and two-qubit RB error per "
        "Clifford, and the corresponding values of our amplitude-damping "
        "γ, phase-damping λ_p, and total depolarizing p."
    )
    sections.append("")
    sections.append(device_regime_table())
    sections.append("")
    sections.append("Citations:")
    sections.append("")
    for dev in DEVICE_REGIMES.values():
        sections.append(f"- **{dev.name}** — {dev.description} {dev.citation}")
    sections.append("")

    sections.append("## A.2 Sampling-range to physical-regime mapping")
    sections.append("")
    sections.append(
        "v1 samples each channel-family parameter from a uniform range. "
        "Below we translate each range into the corresponding device-side "
        "T₁ / T₂ / RB regime. \"Covered\" means the device's calibrated "
        "value falls inside the v1 sampling range; \"OUTSIDE\" means our "
        "training-set sampling range does not include that device's regime."
    )
    sections.append("")
    for ann in all_family_annotations():
        sections.append(f"### {ann.family}")
        sections.append("")
        sections.append(
            f"Code range: ``{ann.family} ∈ [{ann.code_range[0]}, {ann.code_range[1]}]``."
        )
        sections.append("")
        sections.append(f"Physical meaning: {ann.physical_meaning}")
        sections.append("")
        sections.append("| Device | Status |")
        sections.append("|---|---|")
        for dev_name, status in ann.regimes_covered.items():
            sections.append(f"| {dev_name} | {status} |")
        sections.append("")

    sections.append("## A.3 Lindblad-family unit interpretation")
    sections.append("")
    sections.append(
        "The Lindblad family integrates "
        "``L = -i[H, ·] + Σ_k γ_k D[c_k]`` for time t. Sampling ranges:\n"
        "\n"
        "- ω_x, ω_z ∈ U(-0.5, 0.5)\n"
        "- γ_damp ∈ U(0, 0.15) (σ_- collapse)\n"
        "- γ_phase ∈ U(0, 0.12) (σ_z collapse)\n"
        "- t ∈ U(0.05, 1.0)\n"
        "\n"
        "Adopting the unit-time as μs maps these to a NISQ superconducting "
        "regime (Rabi amplitudes in the MHz band, T₁ ≥ 6.7 μs, T_φ ≥ 8.3 μs). "
        "Adopting the unit-time as ms maps the same numbers into the "
        "trapped-ion regime (kHz Rabi, ≥ 6.7 ms coherence). The Lindblad "
        "family is therefore platform-agnostic by design."
    )
    sections.append("")

    sections.append("## A.4 What is NOT covered")
    sections.append("")
    sections.append(
        "The Quantinuum / IonQ trapped-ion devices have RB errors ~1e-5 "
        "and effectively infinite T₁ at the gate-time scale. v1's lower "
        "sampling bound for amplitude / phase damping is exactly zero, so "
        "the trained model sees the trapped-ion regime as part of its "
        "support. However, the *training distribution density* near zero "
        "is light (uniform). For PRXQ a follow-up experiment in P0.1 "
        "evaluates real Quantinuum and IonQ noise to confirm in-support "
        "performance is not penalised."
    )
    sections.append("")

    out.write_text("\n".join(sections))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
